# Generated by Django 4.1.3 on 2022-12-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_paymentmaster'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1000)),
                ('dateOfOrder', models.DateTimeField()),
                ('details', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.userinfo')),
            ],
            options={
                'db_table': 'OrderMaster',
            },
        ),
    ]
