# Generated by Django 4.1.3 on 2022-12-13 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_ordermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='dateOfOrder',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
